name: 'Open a Github issue'
description: 'Open de issue'
author: 'llg'

# Define your inputs here.
inputs:
  token:
    description: 'Github Token'
    required: true
  title:
    description: 'Issue Title'
    required: true
  body:
    description: 'Issue body'
  assignees:
    description: 'Issue Assignees'
  who-to-greed:
    description: 'Site https to test'
    required: true

# Define your outputs here.
outputs:
  checked:
    description: 'Check certificate result'

runs:
  using: node20
  main: dist/index.js
