name: Check certificate

on:
  workflow_call:
    inputs:
      which-url:
        description: "https url to check"
        type: string
        required: true
    outputs:
      date:
        description: "https ssl end" 
        value: ${{ jobs.test.outputs.msg}}     

permissions:
  issues: write

jobs:
  test:
    name: Test https
    runs-on: thinkpad
    outputs:
      msg: ${{steps.msg-add.outputs.msg-out}}

    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: ./
        id: issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: Test issue
          body: Test issue body
          assignees: |
            llegouve78
          who-to-greed: ${{ github.event.inputs.which-url}}
      - run:  echo "msg-out=${{ steps.issue.outputs.checked }}" >> $GITHUB_OUTPUT
        id: msg-add 