name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read


  test:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: Test issue
          body: Test issue body
          assignees: |
            llg

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.issue }}"
