name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  units: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  test:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: Test issue
          body: Test issue body
          assignees: |
            llg

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.issue }}"
